### ISSUE TITLE
Broken links in Resources page

### ISSUE THREAD

**Issue by maryryan** [datascijedi/website#10]
These two links are broken, and I haven't been able to find the pages/resources they're meant to reference:

- https://library.osu.edu/researchcommons/2020/06/17  ([Web view](https://emory-my.sharepoint.com/personal/nedean_emory_edu/_layouts/OneNote.aspx?id=%2Fpersonal%2Fnedean_emory_edu%2FDocuments%2FOneNote%20-%20Service&wd=target%28Diversity.one%7C2A5298B0-241E-4C4D-A0D9-B1DEC0F51F48%2FPapers%7C2A0C7C6F-CCE9-45C5-A6D9-83AB5C0E6F17%2F%29))

- https://medicine-matters.blogs.hopkinsmedicine.org/files/2016  ([Web view](https://emory-my.sharepoint.com/personal/nedean_emory_edu/_layouts/OneNote.aspx?id=%2Fpersonal%2Fnedean_emory_edu%2FDocuments%2FOneNote%20-%20Service&wd=target%28Diversity.one%7C2A5298B0-241E-4C4D-A0D9-B1DEC0F51F48%2FPapers%7C2A0C7C6F-CCE9-45C5-A6D9-83AB5C0E6F17%2F%29))

**Comment by ravimakhija** [comment]
For the medicine-matters blog, it looks like the link might be cut off? The following link works for browsing 2016 blog posts (e.g. by omitting "files" from the URL), which might help:

https://medicine-matters.blogs.hopkinsmedicine.org/2016/

For others' reference, these links were removed on commit 40ff8b7f77931ce7a17bc59c323e19951acd818d and 8139b0c06ee7f81b7572d852db7a001e34b0f362 (both already merged into main).

**Comment by ravimakhija** [comment]
Hi @maryryan, below are updated links you can use (thanks to Natalie for finding them):

- https://guides.osu.edu/africana/blacklivesmatterdata
- https://link.springer.com/article/10.1007/s40615-016-0288-y

**Comment by maryryan** [comment]
Added the new links and changed the link style so that we're hyperlinking the entire sentence describing the link resource, as this is better for screen readers
