### ISSUE TITLE
Twitter embed stopped working

### ISSUE THREAD

**Issue by ravicodelabs** [datascijedi/website#100]
The embedded Twitter timeline stopped showing tweets and now says "Nothing to see here - yet". 

It appears this was caused by a change from Twitter's side, and it is currently unclear whether a fix will restore the prior behavior, or if the behavior will be changing. More discussion here: https://twittercommunity.com/t/again-list-widget-says-nothing-to-see-here-yet-if-logged-out/198782/111

Possible solutions that come to mind are to (1) just remove the timeline, (2) remove the timeline from the website and bring it back if we see the behavior is restored, (3) leave the broken timeline up for now and wait some time to see if the tweets show up again, or (4) switch to some other embedded social media if that option exists. Open to any suggestions!

**Comment by ravicodelab** [comment]
The embedded Twitter timeline was removed in PR #101 as a temp fix, with the idea of reinstating the timeline if the behavior is restored (on Twitter's side) at some point in the future.

**Comment by ravicodelabs** [comment]
The current behavior seems to be that the embedded timeline works as expected so long as the datascijedi.org website visitor is logged into their Twitter account on the same browser. 

So, I believe the question is whether (1) we want to have an embedded timeline that works when the website visitors are logged into Twitter, but otherwise see "Nothing to see here - yet", or (2) if we want to continue to not include the embedded timeline (the Twitter profile is still, of course, linked from the social media icons in the top right).

**Comment by ravicodelabs** [comment]
It was decided to leave the Twitter timeline off indefinitely to avoid having the website look broken for visitors not logged into Twitter, so closing this issue.
