### ISSUE TITLE
alt text isn't working

### ISSUE THREAD

**Issue by hardin47** [datascijedi/website#102]
Hi, @maryryan.  Thanks for the work you've done to get the work out about JEDI at JSM.  Your handout is fantastic!  Unfortunately, the alt text doesn't seem to be working.  (Maybe it's just my browser.  Does it work on your browser?)

![image](https://github.com/datascijedi/website/assets/7210585/6fe1c857-5242-42ed-a102-25804373e10b)

I don't know how to fix the syntax you used, but when I want alt text on a figure using quarto, I do the following.  It might work for you?

```
::: {.g-col-4}
    ```{r fig.cap = "write a caption here", fig.alt = "alt text goes here "}
    knitr::include_graphics("../imagefolder/imagename.jpg")
    ```
:::
```

**Comment by maryryan** [comment]
Hi @hardin47 - thanks for the heads up. I accidentally had some double quotation marks in the alt-text that was messing with the formatting. Should be fixed now!
