### ISSUE TITLE
add location info for JEDI OG networking event

### ISSUE THREAD

**Issue by hardin47** [datascijedi/website#103]
I found it super difficult to find the **location** info about the JEDI OG networking event.  maybe you could add it to the website?

JEDI OG Networking Event
Tuesday, Aug 8: 10:30 AM - 12:00 PM
ASA Meetings and Events 
Delta Hotels by Marriott Toronto 
Room: D - Harbourfront 
Main Sponsor
Justice, Equity, Diversity, and Inclusion Outreach Group
Co Sponsors
ASA LGBTQ+ Advocacy Committee

**Comment by brtarran** [comment]
Done in 3eb63b7
