### ISSUE TITLE
Add documentation for content updates

### ISSUE THREAD

**Issue by ravicodelabs** [datascijedi/website#15]
To Do: Add documentation on how to update the website update for content editors (e.g. for both non-technical and technical folks). 

- This documentation could potentially live in the [CONTRIBUTING.md](https://github.com/datascijedi/website/blob/main/CONTRIBUTING.md) file. 
- The website update process should be as convenient and intuitive as possible.

**Comment by rycoley** [comment]
I need to update with the most recent JEDI Corner, and I will document that process. I hope to do this by the end of the week. I was thinking I might have separate .md files describing in detail how to update the JEDI Corner and the webinars.

**Comment by rycoley** [comment]
I added an upcoming webinar and wrote instructions for how to do this in the CONTRIBUTING.md. I will do the same with new JEDI Corners and past webinars when it comes time to update those.

**Comment by rycoley** [comment]
Note to make sure that alt text and accessibility features are included in documentation

**Comment by ravicodelabs** [comment]
> Note to make sure that alt text and accessibility features are included in documentation

This has been added via PR #110.
