### ISSUE TITLE
Broken image in top left

### ISSUE THREAD

**Issue by ravimakhija** [datascijedi/website#18]
It looks like there is a broken image in the top left of the website. The broken image is clearly noticeable in Safari, while in Chrome it can be detected with a mouse over. 

Hence, probably either the image link should be fixed, or the image should be removed from the website.

**Comment by fatso-jetson** [comment]
The referenced image is missing from the images folder. I've tried both of the logo files in the images folder, and neither work as a header image (too small, text not legible).

I think we need a logo there, or a website title, as currently there is nothing in the navbar to badge the site as the DataSci JEDI site. If someone is able to send me the source file for the group logo, I could work something up in Photoshop/Illustrator.

**Comment by ravimakhija** [comment]
Hmm not sure, good question. I was able to use the logo files in the images folder for the favicon. 

Perhaps @rycoley or @mine-cetinkaya-rundel might know where the logo's source image files are.

**Comment by mine-cetinkaya-rundel** [comment]
I believe it was meant to show https://github.com/datascijedi/website/blob/main/images/jedi-logo-square.png. Looks like it's currently going to `images/jedi-logo.png` which doesn't exist.

**Comment by fatso-jetson** [comment]
I've added the jedi-logo-square image on `94f0df9`. If the source file can be located, I can work on versions that fit better with the dark and light site theme.

**Comment by ravimakhija** [comment]
Thanks Brian!
