### ISSUE TITLE
Upcoming webinar display

### ISSUE THREAD

**Issue by rycoley** [datascijedi/website#33]
The upcoming webinar grid display looks crowded and is difficult to read. Is there a better listing display option?

**Comment by rycoley** [comment]
Note: it looks ok on the home website. It is the display on https://datascijedi.github.io/website/webinars.html that I am worried about

**Comment by mine-cetinkaya-rundel** [comment]
Instead of a grid, we can use the default listing layout. It would look like the following:

<img width="1021" alt="Screenshot 2023-01-13 at 11 57 18 PM" src="https://user-images.githubusercontent.com/5965649/212456661-1f0bed06-3025-44d5-a48e-ac040f720988.png">

**Comment by fatso-jetson** [comment]
I agree with Mine. This is the best display option.
