### ISSUE TITLE
Use deep search in dynamic GitHub script

### ISSUE THREAD

**Issue by ravimakhija** [datascijedi/website#35]
Using recursive search (or more generally, deep search) will allow the script to pick up any HTML files in `_site`, which is more robust to future changes than the current approach of explicitly specifying multiple directories and doing a shallow search on each of them. For instance, if we reorganize some of the `qmd` files by placing them in a new directory, the current script would have to be modified, whereas a recursive search should pick them up automatically without any additional changes to the dynamic gh script needed. 

Also, the fallback link is currently being used for files not located at the root of the `_site` directory. Doing a recursive search can help locate more source files by leveraging the base paths, which can then be used for more page-specific GitHub links instead of fallback links.

**Comment by mine-cetinkaya-rundel** [comment]
Is this for the link to edit any page on GitHub, even when there is no toc?

**Comment by ravimakhija** [comment]
> Is this for the link to edit any page on GitHub, even when there is no toc?

Yup. The main motivation for a custom solution is that currently Quarto couples the `toc` with their "Edit GitHub page" functionality. 

The current implementation is in [dynamic_github_edit.js](https://github.com/datascijedi/website/blob/main/dynamic_github_edit.js) and you will notice in the script a variable `build_path_list` which specifies where to look for HTML files. The idea of this new issue is to use a deep/recursive search in `_site` (and excluding `site_libs` and `images`) so that we don't need to update a `build_path_list` if and when HTML files are rendered in new directories in the future. 

I don't think this is critical for pre-launch since there is already a fallback functionality to the general repo for files that aren't picked up via `build_path_list`, but it would be a nice-to-have. 

On a somewhat related note, I was thinking it may be more intuitive if the GitHub icon in the footer points to the root of the repo instead of also going directly to edit a source file; the "Edit this page" can be kept to go directly to edit a source file. It might also be nice to add a special case for the article list, e.g. so that we have a "Edit article list" in the footer.

**Comment by mine-cetinkaya-rundel** [comment]
I asked about this to the Quarto team and I believe a built-in solution is coming down the pipeline soon. I can update it when it's in Quarto, and for now, what we have is good I think.

I agree that the GitHub icon at the bottom is redundant. There's actually a GitHub icon in the navbar and I just pointed that to the repo with 69bcc9cc640ce56ce0a542ee833f0684eea4c6ba, and removed the icon from the bottom. I think it looks cleaner now.

We can leave this issue open till we have a native Quarto fix for the "Edit this page" without a sidebar.

**Comment by ravimakhija** [comment]
> ...built-in solution is coming down the pipeline soon.

Nice! If there is an issue/pull request from the Quarto project it would be nice to link to that from here as well. 

> ...for now, what we have is good I think.

The recursive search should be a quick addition. If it is implemented before the Quarto fix becomes available, we can just close this and open a new issue for moving to the Quarto built-in version when it is ready. 

> ...and removed the icon from the bottom.

Looks like the footer vertical alignment was affected. I can fix that if you'd like.

**Comment by mine-cetinkaya-rundel** [comment]
Fixing the vertical alignment sounds good, thank you!

Here is the relevant Quarto issue: https://github.com/quarto-dev/quarto-cli/issues/2142

**Comment by ravimakhija** [comment]
For sure! Vertical alignment fixed in PR #39.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you @ravimakhija!

**Comment by ravimakhija** [comment]
Hi - the deep search is added with PR #42. And, issue #43 was opened for the expected transition to the Quarto built-in approach.
