### ISSUE TITLE
Are there any other top bar nav elements we need?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [datascijedi/website#5]
<img width="1275" alt="Screen Shot 2022-11-18 at 12 28 27 PM" src="https://user-images.githubusercontent.com/5965649/202765682-2e0fe27d-4c43-47f2-8376-3b4876c6f281.png">

**Comment by ravimakhija** [comment]
@mine-cetinkaya-rundel I think this issue could be closed, since we've recently incorporated the latest navbar changes.

**Comment by mine-cetinkaya-rundel** [comment]
Agreed!
