### ISSUE TITLE
Add new form for announcements

### ISSUE THREAD

**Issue by ravicodelabs** [datascijedi/website#64]
To Do: 
- Get javascript embed code from @zzlalo. (The Jotform JavaScript embed code is preferred over the `iFrame` embed code, as it stays current with any backend form updates). 
- Add the new form to the website.

**Comment by ravimakhija** [comment]
I believe the below should work for embedding the announcements form:

```html
<script type="text/javascript" src="https://form.jotform.com/jsform/230625164644151"></script>
```

This is based on the embed code taken from the temporary Google sites website, which I'm including below for reference:

```html
<iframe id="JotFormIFrame-230625164644151" title="JEDI Announcements" onload="window.parent.scrollTo(0,0)" 
allowtransparency="true" allowfullscreen="true" allow="geolocation; microphone; camera" 
src="https://form.jotform.com/230625164644151?jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.lb.en.Oupypiulh58.O%2Fd%3D1%2Frs%3DAHpOoo_CVmSAWqMsGCHgMRyaSvlE8hY6sw%2Fm%3D__features__&amp;isIframeEmbed=1" 
frameborder="0" style="min-width: 100%; max-width: 100%; height: 4323px; border: none;" scrolling="no">
</iframe>
```

So that leaves the second part, e.g. figuring out how to incorporate this in the new website design.

**Comment by ravicodelabs** [comment]
Added in PR #117.
