### ISSUE TITLE
Video link not working for "Letters of recommendation" webinar

### ISSUE THREAD

**Issue by fatso-jetson** [datascijedi/website#7]
In "webinars\past\2022-09-11-letters-of-recommendation.qmd", the video link is not displaying correctly. The YouTube upload does not allow embedding/playback outside YouTube. This needs to be fixed via the YouTube account, I think.

**Comment by rycoley** [comment]
I will ask the youtube account owner to fix it. I think we will also have that problem with the graduate school admissions webinar

**Comment by rycoley** [comment]
Donna made the changes to the videos on youtube. Videos play now.
