### ISSUE TITLE
Graduate school admissions webinar not included with past webinars

### ISSUE THREAD

**Issue by rycoley** [datascijedi/website#9]
I created a new listing for a webinar and put it in the past webinars folder, but it is not showing on the webpage. I don't know where else I need to update the code for it to be included in the list.

**Comment by fatso-jetson** [comment]
The problem looks to be that the new webinar entry isn't saved as a .qmd file. I'm only on the GitHub app at the moment, but will take a look at the files properly later.

**Comment by fatso-jetson** [comment]
Fixed in `56f85d8`
