### ISSUE TITLE
Remove web pages that are works in progress

### ISSUE THREAD

**Issue by ravimakhija** [datascijedi/website#93]
Currently `mission.qmd` and `welcome.qmd` are on the main branch and so are rendered with the live website, but they are still works in progress. So, we should remove them, or perhaps move them to a feature branch. fyi @mine-cetinkaya-rundel

**Comment by mine-cetinkaya-rundel** [comment]
I think these are ok to remove. They're there from the first draft of the page and aren't being pulled in via `_quarto.yml` anyway.

**Comment by ravimakhija** [comment]
Removed via commit 9618824f562f382a8b723a0fff6ad6d18260f48c. Also removed `history.qmd`, which was also unfinished.
